name = "hritvikac-connect4"
main = "src/index.js"
compatibility_date = "2026-09-17"

[vars]
FRONTEND_ORIGIN = "https://hritvikac.github.io"

[durable_objects]
bindings = [
  { name = "GAME", class_name = "GameLobby" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameLobby"]
